// <auto-generated />
using System;
using DPBack.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DPBack.Infrastructure.Migrations.ProductStoreDb
{
    [DbContext(typeof(ProductStoreDbContext))]
    [Migration("20260227133935_ProductsInit")]
    partial class ProductsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DPBack.Infrastructure.Entities.BusinesscardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Finish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Businesscards");
                });

            modelBuilder.Entity("DPBack.Infrastructure.Entities.BusinesscardFinishTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BusinesscardCoating");
                });

            modelBuilder.Entity("DPBack.Infrastructure.Entities.BusinesscardPaperTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Thickness")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BusinessCardPaper");
                });
#pragma warning restore 612, 618
        }
    }
}
